version: '3.8'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "host=postgres user=user password=pass dbname=gorm port=5432 sslmode=disable"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


